version: "3.8"

services:
  backend:
    container_name: hazy_backend
    build: .
    ports:
      - 5000:8000
      - 5556:5555
    environment:
      - CELERY__BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@celerybackend:5672//
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    env_file:
      - .env
    volumes:
      - .:/app
      - pip-cache:/root/.cache/pip
    networks:
      - hazy_network
    restart: always
    depends_on:
      - celerybackend

  celerybackend:
    image: rabbitmq:management-alpine
    container_name: hazy_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 30s
      retries: 50
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: always
    networks:
      - hazy_network

volumes:
  pip-cache:
    name: pip-cache

networks:
  hazy_network:
    external: true
